version: '3.8'

services:

  mongo-db:
    image: mongo:6.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rest-clean-architecture
      MONGO_INITDB_ROOT_PASSWORD: e8c3f8f1e98a03b877ffb181ede37e3f74e31ce2
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

# postgres-db:
#   image: postgres:15.3
#   restart: always
#   environment:
#     POSTGRES_USER: postgres
#     POSTGRES_DB: my-db
#     POSTGRES_PASSWORD: 123456
#   volumes:
#     - ./postgres:/var/lib/postgresql/data
#   ports:
#     - 5432:5432
